stages:
  - build
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${ENV_MAIN} .env
    - cp ${ENV_TEST} .test.env
  script:
    - docker build -t booking_app_image .

deploy-job:
  stage: deploy
  script:
    - docker compose -f docker-compose-ci.yml up -d
