  services:
    booking_backend_service:
      container_name: "booking_backend"
      build:
        context: .
      networks:
        - "booknet"
      # ports:
        # - "8888:8000"
      env_file:
        - ".env"
      volumes:
        - ./src/media/images:/app/src/media/images

    booking_celery_worker_service:
      container_name: "booking_celery_worker"
      build:
        context: .
      env_file:
        - ".env"
      networks:
        - "booknet"
      volumes:
        - ./src/media/images:/app/src/media/images
      command: "poetry run celery --app=src.tasks.app:celery_app worker -l INFO"

    booking_celery_beat_service:
      container_name: "booking_celery_beat"
      build:
        context: .
      env_file:
        - ".env"
      networks:
        - "booknet"
      command: "poetry run celery --app=src.tasks.app:celery_app beat -l INFO"

  networks:
    booknet:
      external: "true"
